version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: banking-postgres
    environment:
      POSTGRES_PASSWORD: 757575
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: banking-redis-compose
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: banking-rabbitmq-compose
    ports:
      - "5672:5672"
      - "15672:15672"

  discovery-server:
    build:
      context: .
      args:
        SERVICE_NAME: discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      SERVER_PORT: 8761

  api-gateway:
    build:
      context: .
      args:
        SERVICE_NAME: api-gateway
    container_name: api-gateway
    ports:
      - "8085:8085"
    environment:
      SERVER_PORT: 8085
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server

  auth-service:
    build:
      context: .
      args:
        SERVICE_NAME: auth-service
    container_name: auth-service
    environment:
      SERVER_PORT: 9090
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/BankingAuthDB
      SPRING_DATASOURCE_PASSWORD: 757575
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    depends_on:
      - postgres
      - discovery-server

  account-service:
    build:
      context: .
      args:
        SERVICE_NAME: account-service
    container_name: account-service
    environment:
      SERVER_PORT: 9091
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/BankingAccountDB
      SPRING_DATASOURCE_PASSWORD: 757575
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    depends_on:
      - postgres
      - discovery-server

  transfer-service:
    build:
      context: .
      args:
        SERVICE_NAME: transfer-service
    container_name: transfer-service
    environment:
      SERVER_PORT: 9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/BankingTransferDB
      SPRING_DATASOURCE_PASSWORD: 757575
      SPRING_RABBITMQ_HOST: rabbitmq
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    depends_on:
      - postgres
      - rabbitmq
      - discovery-server

  transaction-service:
    build:
      context: .
      args:
        SERVICE_NAME: transaction-service
    container_name: transaction-service
    environment:
      SERVER_PORT: 9093
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/BankingTransactionDB
      SPRING_DATASOURCE_PASSWORD: 757575
      SPRING_RABBITMQ_HOST: rabbitmq
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    depends_on:
      - postgres
      - rabbitmq
      - discovery-server

  notification-service:
    build:
      context: .
      args:
        SERVICE_NAME: notification-service
    container_name: notification-service
    environment:
      SERVER_PORT: 9094
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/BankingNotificationDB
      SPRING_DATASOURCE_PASSWORD: 757575
      SPRING_RABBITMQ_HOST: rabbitmq
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    depends_on:
      - postgres
      - rabbitmq
      - discovery-server

  fraud-detection-service:
    build:
      context: .
      args:
        SERVICE_NAME: fraud-detection-service
    container_name: fraud-detection-service
    environment:
      SERVER_PORT: 9095
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/BankingFraudDB
      SPRING_DATASOURCE_PASSWORD: 757575
      SPRING_DATA_REDIS_HOST: redis
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    depends_on:
      - postgres
      - redis
      - discovery-server

volumes:
  postgres_data: